version: "2"
run:
  timeout: 15m
  concurrency: 10
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - perfsprint
    - testifylint
    - wastedassign
    # - depguard
    # - prealloc
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - hugeParam # Micro-optimisations
        - rangeValCopy # Micro-optimisations
        - ifElseChain # Mostly false positives
        - ptrToRefParam # False positives?
        - importShadow # Probably not worth the hassle...
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    nakedret:
      max-func-lines: 60
    revive:
      confidence: 3
      severity: warning
    testifylint:
      disable-all: true
      enable:
        - nil-compare
        - compares
        - error-is-as
        - bool-compare
        - empty
        - len
        - expected-actual
        - error-nil
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
