version: "3"

tasks:
  web:
    desc: "Build the web frontend"
    dir: web
    cmds:
      - "{{.WEB_BUILD_CMD}}"

  server:
    desc: "Build the Go server binary"
    cmds:
      - "{{.GO_BUILD_CMD}} ./cmd/monolith"

  win:
    desc: "Build for Windows (amd64)"
    cmds:
      - task: web
      - task: server
    env:
      GOOS: windows
      GOARCH: amd64

  linux:
    desc: "Build for Linux (amd64)"
    cmds:
      - task: web
      - "{{.GO_BUILD_CMD}} ./cmd/monolith"
    env:
      GOOS: linux
      GOARCH: amd64

  docker:
    desc: "Build Docker image"
    cmds:
      - docker build -t monolith:latest .

  all:
    desc: "Build for all platforms"
    cmds:
      - task: win
      - task: linux
      - task: docker
