// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (username, name, email, password, is_admin, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, username, email, name, avatar, is_admin, language, theme, timezone,
          last_seen_at, status, created_at, updated_at
`

type CreateAccountParams struct {
	Username string
	Name     pgtype.Text
	Email    string
	Password pgtype.Text
	IsAdmin  pgtype.Bool
	Status   string
}

type CreateAccountRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.IsAdmin,
		arg.Status,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitedAccount = `-- name: CreateInvitedAccount :one
INSERT INTO account (username, email, name, is_admin, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'pending', NOW(), NOW())
RETURNING id, username, email, name, avatar, is_admin, language, theme, timezone,
          last_seen_at, status, created_at, updated_at
`

type CreateInvitedAccountParams struct {
	Username string
	Email    string
	Name     pgtype.Text
	IsAdmin  pgtype.Bool
}

type CreateInvitedAccountRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) CreateInvitedAccount(ctx context.Context, arg CreateInvitedAccountParams) (CreateInvitedAccountRow, error) {
	row := q.db.QueryRow(ctx, createInvitedAccount,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.IsAdmin,
	)
	var i CreateInvitedAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const disableAccount = `-- name: DisableAccount :exec
UPDATE account SET status = 'disabled', updated_at = NOW() WHERE id = $1
`

func (q *Queries) DisableAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableAccount, id)
	return err
}

const enableAccount = `-- name: EnableAccount :exec
UPDATE account SET status = 'active', updated_at = NOW() WHERE id = $1
`

func (q *Queries) EnableAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, email, name, avatar, is_admin, language, theme, timezone,
       last_seen_at, status, created_at, updated_at
FROM account
WHERE id = $1 AND status = 'active'
`

type GetAccountRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, email, name, is_admin, language, theme, timezone,
       last_seen_at, status, created_at, updated_at
FROM account
WHERE id = $1 AND status = 'active'
`

type GetAccountByIDRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByIDWithPassword = `-- name: GetAccountByIDWithPassword :one
SELECT id, password
FROM account
WHERE id = $1 AND status = 'active'
`

type GetAccountByIDWithPasswordRow struct {
	ID       uuid.UUID
	Password pgtype.Text
}

func (q *Queries) GetAccountByIDWithPassword(ctx context.Context, id uuid.UUID) (GetAccountByIDWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getAccountByIDWithPassword, id)
	var i GetAccountByIDWithPasswordRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, username, email, name, password, is_admin, language, theme, timezone,
       last_seen_at, status, created_at, updated_at
FROM account
WHERE (email = $1 OR username = $1) AND status = 'active'
`

type GetAccountByLoginRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Password   pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) GetAccountByLogin(ctx context.Context, email string) (GetAccountByLoginRow, error) {
	row := q.db.QueryRow(ctx, getAccountByLogin, email)
	var i GetAccountByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT id, username, email, name, avatar, is_admin, language, theme, timezone,
       last_seen_at, status, created_at, updated_at
FROM account
ORDER BY created_at DESC
`

type GetAccountsRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) GetAccounts(ctx context.Context) ([]GetAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsRow
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.Avatar,
			&i.IsAdmin,
			&i.Language,
			&i.Theme,
			&i.Timezone,
			&i.LastSeenAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerAccount = `-- name: RegisterAccount :one
INSERT INTO account (username, email, name, password, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, username, email, name, is_admin, language, theme, timezone,
          last_seen_at, status, created_at, updated_at
`

type RegisterAccountParams struct {
	Username string
	Email    string
	Name     pgtype.Text
	Password pgtype.Text
}

type RegisterAccountRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) RegisterAccount(ctx context.Context, arg RegisterAccountParams) (RegisterAccountRow, error) {
	row := q.db.QueryRow(ctx, registerAccount,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.Password,
	)
	var i RegisterAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account
SET username = $1, name = $2, email = $3, updated_at = NOW()
WHERE id = $4 AND status = 'active'
RETURNING id, username, email, name, avatar, is_admin, language, theme, timezone,
          last_seen_at, status, created_at, updated_at
`

type UpdateAccountParams struct {
	Username string
	Name     pgtype.Text
	Email    string
	ID       uuid.UUID
}

type UpdateAccountRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.ID,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.Avatar,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE account SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE account SET password = $1, updated_at = NOW() WHERE id = $2
`

type UpdatePasswordParams struct {
	Password pgtype.Text
	ID       uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE account
SET language = $1, theme = $2, timezone = $3, updated_at = NOW()
WHERE id = $4 AND status = 'active'
RETURNING id, username, email, name, is_admin, language, theme, timezone,
          last_seen_at, status, created_at, updated_at
`

type UpdatePreferencesParams struct {
	Language pgtype.Text
	Theme    pgtype.Text
	Timezone pgtype.Text
	ID       uuid.UUID
}

type UpdatePreferencesRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UpdatePreferencesRow, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.Language,
		arg.Theme,
		arg.Timezone,
		arg.ID,
	)
	var i UpdatePreferencesRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.IsAdmin,
		&i.Language,
		&i.Theme,
		&i.Timezone,
		&i.LastSeenAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT id FROM account WHERE email = $1 OR username = $2
`

type UserExistsParams struct {
	Email    string
	Username string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, userExists, arg.Email, arg.Username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
