// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_session.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupSessions = `-- name: CleanupSessions :exec
DELETE FROM auth_session
WHERE revoked_at IS NOT NULL
`

func (q *Queries) CleanupSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSessions)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_session (token, prev_token, account_id, user_agent, client_ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, prev_token, account_id, user_agent, client_ip, token_seen, seen_at, created_at, rotated_at, revoked_at
`

type CreateSessionParams struct {
	Token     string
	PrevToken string
	AccountID uuid.UUID
	UserAgent string
	ClientIp  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Token,
		arg.PrevToken,
		arg.AccountID,
		arg.UserAgent,
		arg.ClientIp,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.PrevToken,
		&i.AccountID,
		&i.UserAgent,
		&i.ClientIp,
		&i.TokenSeen,
		&i.SeenAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthContextByToken = `-- name: GetAuthContextByToken :one
SELECT
    s.id as session_id,
    s.token as session_token,
    s.account_id,
    a.email as account_email,
    a.is_admin as account_is_admin,
    a.status as account_status,
    s.created_at as session_created,
    s.rotated_at as session_rotated,
    s.revoked_at as session_revoked
FROM auth_session s
INNER JOIN account a ON s.account_id = a.id AND a.status = $3
WHERE (s.token = $1 OR s.prev_token = $2)
`

type GetAuthContextByTokenParams struct {
	Token     string
	PrevToken string
	Status    string
}

type GetAuthContextByTokenRow struct {
	SessionID      uuid.UUID
	SessionToken   string
	AccountID      uuid.UUID
	AccountEmail   string
	AccountIsAdmin pgtype.Bool
	AccountStatus  string
	SessionCreated time.Time
	SessionRotated time.Time
	SessionRevoked *time.Time
}

func (q *Queries) GetAuthContextByToken(ctx context.Context, arg GetAuthContextByTokenParams) (GetAuthContextByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthContextByToken, arg.Token, arg.PrevToken, arg.Status)
	var i GetAuthContextByTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionToken,
		&i.AccountID,
		&i.AccountEmail,
		&i.AccountIsAdmin,
		&i.AccountStatus,
		&i.SessionCreated,
		&i.SessionRotated,
		&i.SessionRevoked,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, token, account_id, user_agent, client_ip, created_at, rotated_at, revoked_at
FROM auth_session
WHERE token = $1 OR prev_token = $2
`

type GetSessionByTokenParams struct {
	Token     string
	PrevToken string
}

type GetSessionByTokenRow struct {
	ID        uuid.UUID
	Token     string
	AccountID uuid.UUID
	UserAgent string
	ClientIp  string
	CreatedAt time.Time
	RotatedAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, arg.Token, arg.PrevToken)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.AccountID,
		&i.UserAgent,
		&i.ClientIp,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionsByAccountID = `-- name: GetSessionsByAccountID :many
SELECT id, token, account_id, user_agent, client_ip, created_at, rotated_at, revoked_at
FROM auth_session
WHERE account_id = $1 AND revoked_at IS NULL
ORDER BY rotated_at DESC
`

type GetSessionsByAccountIDRow struct {
	ID        uuid.UUID
	Token     string
	AccountID uuid.UUID
	UserAgent string
	ClientIp  string
	CreatedAt time.Time
	RotatedAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) GetSessionsByAccountID(ctx context.Context, accountID uuid.UUID) ([]GetSessionsByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getSessionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsByAccountIDRow
	for rows.Next() {
		var i GetSessionsByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.AccountID,
			&i.UserAgent,
			&i.ClientIp,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_session
SET revoked_at = NOW()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, accountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_session
SET revoked_at = NOW()
WHERE id = $1 AND account_id = $2
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.AccountID)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE auth_session
SET token = $1, prev_token = $2, rotated_at = NOW(), token_seen = FALSE, seen_at = NULL
WHERE id = $3
RETURNING id, token, prev_token, account_id, user_agent, client_ip, token_seen, seen_at, created_at, rotated_at, revoked_at
`

type RotateSessionParams struct {
	Token     string
	PrevToken string
	ID        uuid.UUID
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.Token, arg.PrevToken, arg.ID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.PrevToken,
		&i.AccountID,
		&i.UserAgent,
		&i.ClientIp,
		&i.TokenSeen,
		&i.SeenAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}
