// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         uuid.UUID
	Username   string
	Email      string
	Name       pgtype.Text
	Avatar     pgtype.Text
	Password   pgtype.Text
	IsAdmin    pgtype.Bool
	Language   pgtype.Text
	Theme      pgtype.Text
	Timezone   pgtype.Text
	LastSeenAt *time.Time
	Status     string
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}

type AuthSession struct {
	ID        uuid.UUID
	Token     string
	PrevToken string
	AccountID uuid.UUID
	UserAgent string
	ClientIp  string
	TokenSeen bool
	SeenAt    *time.Time
	CreatedAt time.Time
	RotatedAt time.Time
	RevokedAt *time.Time
}
