// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupSessions(ctx context.Context) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateInvitedAccount(ctx context.Context, arg CreateInvitedAccountParams) (CreateInvitedAccountRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DisableAccount(ctx context.Context, id uuid.UUID) error
	EnableAccount(ctx context.Context, id uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountByIDWithPassword(ctx context.Context, id uuid.UUID) (GetAccountByIDWithPasswordRow, error)
	GetAccountByLogin(ctx context.Context, email string) (GetAccountByLoginRow, error)
	GetAccounts(ctx context.Context) ([]GetAccountsRow, error)
	GetAuthContextByToken(ctx context.Context, arg GetAuthContextByTokenParams) (GetAuthContextByTokenRow, error)
	GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error)
	GetSessionsByAccountID(ctx context.Context, accountID uuid.UUID) ([]GetSessionsByAccountIDRow, error)
	RegisterAccount(ctx context.Context, arg RegisterAccountParams) (RegisterAccountRow, error)
	RevokeAllUserSessions(ctx context.Context, accountID uuid.UUID) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) (AuthSession, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error)
	UpdateLastSeen(ctx context.Context, id uuid.UUID) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UpdatePreferencesRow, error)
	UserExists(ctx context.Context, arg UserExistsParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
